[project]
name = "fastapi-cloud-storage"
version = "0.1.0"
description = "A powerful, extensible, and async-ready cloud object storage backend for FastAPI."
readme = "README.md"
authors = [
    { name = "stabldev", email = "thestabldev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
s3 = ["aioboto3>=15.4.0"]

[tool.uv.build-backend]
module-root = "src"
module-name = "cloud_storage"

[tool.pyright]
reportMissingTypeStubs = "none"
reportUnknownMemberType = "none"
reportUnusedCallResult = "none"
reportUnknownVariableType = "none"
reportAny = "none"
reportExplicitAny = "none"

[build-system]
requires = ["uv_build>=0.8.20,<0.9.0"]
build-backend = "uv_build"
